version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    ports:
      - "8096:8096"
    volumes:
      - /media/pi/barracuda/jellyfin-config:/config
      - /media/pi/barracuda/jellyfin-cache:/cache
      - /media/pi/barracuda/media:/media
