version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    ports:
      - "8096:8096"
    volumes:
      - ~/jellyfin/config:/config
      - ~/jellyfin/cache:/cache
      - /media/mg/barracuda/media:/media
