version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    ports:
      - "8096:8096"
    volumes:
      - /media/mg/barracuda/jellyfin-config:/config
      - /media/mg/barracuda/jellyfin-cache:/cache
      - /media/mg/barracuda/media:/media
