---
- name: Update/upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: 'yes'
- name: Install apt packages
  become: true
  apt:
    name:
      - python-apt
      - tmux
      - fzf
      - nmap
      - jq
      - ranger
- name: Install pip packages
  become: true
  pip:
    executable: pip3
    name:
      - docker
      - docker-compose
- name: Copy bash config
  copy:
    src: bash_config.bash
    dest: "{{ ansible_env.HOME }}/bash_config.bash"
- name: Add bash config to .profile
  lineinfile:
    path: "{{ ansible_env.HOME }}/.profile"
    state: present
    line: '[ -f "$HOME/bash_config.bash" ] && source "$HOME/bash_config.bash"'
- name: Clone homelab repo
  git:
    repo: 'https://github.com/matthewgrossman/homelab.git'
    dest: "{{ ansible_env.HOME }}/homelab"
