---
- name: Setup raspberrypi4
  hosts: all
  become: true
  roles:
    - common
  tasks:
    - name: Enable VNC
      shell: raspi-config nonint do_vnc 0
    - name: Enable SSH
      shell: raspi-config nonint do_ssh 0
    - name: Set wifi country
      shell: raspi-config nonint do_wifi_country US
    - name: Set keyboard
      shell: raspi-config nonint do_configure_keyboard US
    - name: Set timezone
      shell: raspi-config nonint do_change_timezone America/Los_Angeles
    - name: Set locale
      shell: raspi-config nonint do_change_locale en_US.UTF-8
    - name: Download Docker convenience script
      get_url:
        url: "https://get.docker.com"
        dest: /etc/get-docker.sh
        mode: 0755
      register: dockerinstall
    - name: Execute Docker convenience script
      become: true
      shell: /etc/get-docker.sh
      when: dockerinstall.changed
    - name: Add pi to docker group
      become: true
      user:
        name: pi
        groups: docker
    - name: Install kernel headers
      become: true
      apt:
        name: raspberrypi-kernel-headers
    - name: Mount barracuda
      ansible.posix.mount:
        path: /media/pi/barracuda
        src: LABEL=barracuda
        fstype: ext4
        state: mounted
    # - name: Add testing apt repo
    #   become: true
    #   apt_repository:
    #     repo: deb http://archive.raspbian.org/raspbian testing main
    # - name: Install wireguard
    #   become: true
    #   apt:
    #     update_cache: true
    #     name: wireguard

