---
- name: Setup VPS
  hosts: all
  become: true
  roles:
    - common
    - docker
    - wireguard
  tasks:
    - name: Install python3 on Debian
      become: true
      apt:
        name: python3-venv

